version: '3'
services:
  memos:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5230
    volumes:
      - ./data:/var/opt/memos
    environment:
      - MEMOS_DRIVER=mysql
      - MEMOS_DSN=${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@tcp(${PANEL_DB_HOST})/${PANEL_DB_NAME}
    image: neosmemo/memos:0.19.1
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true