version: '3'
services:
  flexget:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5050
    volumes:
      - ./data/config:/config
      - ./data/data:/data
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - FG_LOG_LEVEL=info
      - FG_WEBUI_PASSWD=${WEB_PASSWORD}
    image: wiserain/flexget:3.9.16
    labels:  
      createdBy: "Apps"
networks:
  1panel-network:  
    external: true