version: '3'
services:
  alist:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5244
    volumes:
      - ./data:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - DB_TYPE=${PANEL_DB_TYPE}
      - DB_HOST=${PANEL_DB_HOST}
      - DB_PORT=${PANEL_DB_PORT}
      - DB_NAME=${PANEL_DB_NAME}
      - DB_USER=${PANEL_DB_USER}
      - DB_PASS=${PANEL_DB_USER_PASSWORD}
      - CDN=${CDN}
    image: xhofe/alist:v3.30.0
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true