version: '3'
services:
  waline:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8360
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_HOST=${PANEL_DB_HOST}
      - MYSQL_DB=${PANEL_DB_NAME}
      - MYSQL_USER=${PANEL_DB_USER}
      - MYSQL_PASSWORD=${PANEL_DB_USER_PASSWORD}
    image: lizheming/waline:latest
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true