version: '3'
services:
  umami:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    environment:
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - TRACKER_SCRIPT_NAME=random-string.js
      - DATABASE_TYPE=postgresql
    image: ghcr.io/umami-software/umami:postgresql-latest
    labels:
      createdBy: "Apps"
networks:  
  1panel-network:
    external: true